### ISSUE TITLE
Sensor drops off the bus after exiting python code

### ISSUE THREAD

**Issue by Ricker42** [adafruit/Adafruit_CircuitPython_SGP30#42]
Environment:
Raspberry Pi 3B+ running Raspbian GNU/Linux 10 (buster)
qwiic pHat

When executing the demo code found at https://learn.adafruit.com/adafruit-sgp30-gas-tvoc-eco2-mox-sensor/circuitpython-wiring-test#circuitpython-and-python-usage-2980170, if the script is exited using CTRL-C on the keyboard, the SGP30 sensor disappears from the i2c bus, and only comes back by either disconnecting the sensor from the cable and reattaching, or by rebooting the Raspberry Pi.

Two differently marked sensors have shown the same reaction.  One has the "LGt" mark on the chip above the SCL & SDA pin holes, the other has no mark on that chip

**Comment by caternuson** [comment]
Related forum post:
https://forums.adafruit.com/viewtopic.php?t=214828

**Comment by caternuson** [comment]
Set this up to try and recreate the issue. I'm seeing some weirdness with i2cdetect, but the example Python code runs OK each time:
```
(blinka) pi@raspberrypi:~ $ python3 sgp30demo.py 
SGP30 serial # ['0x0', '0x166', '0x642a']
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
^CTraceback (most recent call last):
  File "/home/pi/sgp30demo.py", line 25, in <module>
    time.sleep(1)
KeyboardInterrupt

(blinka) pi@raspberrypi:~ $ python3 sgp30demo.py 
SGP30 serial # ['0x0', '0x166', '0x642a']
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
^CTraceback (most recent call last):
  File "/home/pi/sgp30demo.py", line 25, in <module>
    time.sleep(1)
KeyboardInterrupt

(blinka) pi@raspberrypi:~ $ python3 sgp30demo.py 
SGP30 serial # ['0x0', '0x166', '0x642a']
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
^CTraceback (most recent call last):
  File "/home/pi/sgp30demo.py", line 25, in <module>
    time.sleep(1)
KeyboardInterrupt

(blinka) pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
(blinka) pi@raspberrypi:~ $
```

Can you paste the output you are getting if you try to run the demo back-to-back after a CTRL-C break.

**Comment by Ricker42** [comment]
Took a minute to get the environment reconstituted, but here's the requested output:

`pi@pi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- 58 -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         

pi@pi:~ $ python3 sgp30demo.py 
SGP30 serial # ['0x0', '0x166', '0x76d6']
eCO2 = 65535 ppm 	 TVOC = 0 ppb
eCO2 = 63487 ppm 	 TVOC = 0 ppb
eCO2 = 63487 ppm 	 TVOC = 0 ppb
eCO2 = 65535 ppm 	 TVOC = 0 ppb
^CTraceback (most recent call last):
  File "sgp30demo.py", line 25, in <module>
    time.sleep(1)
KeyboardInterrupt

pi@pi:~ $ python3 sgp30demo.py 
Traceback (most recent call last):
  File "sgp30demo.py", line 14, in <module>
    sgp30 = adafruit_sgp30.Adafruit_SGP30(i2c)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_sgp30.py", line 98, in __init__
    raise RuntimeError("SGP30 Not detected")
RuntimeError: SGP30 Not detected

pi@pi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
`

**Comment by caternuson** [comment]
Are you using a virtual environment? Your prompt does not look adjusted as expected with default behavior:
```
pi@pi:~ $ python3 sgp30demo.py
```
The active venv name is typically included in the prompt. For example, from my test output:
```
(blinka) pi@raspberrypi:~ $ python3 sgp30demo.py 
```
My venv is named `blinka`.

Doesn't seem like something that would explain why your code does not run back-to-back. But if your setup is somehow different, then that may be part of it.

**Comment by Ricker42** [comment]
No this is not a virtual environment.  I am running directly on a Raspberry Pi, as detailed above.  When I said it took time "to get the environment reconstituted", I had to get everything plugged back together and powered up, I had moved it aside to work on another project.

**Comment by caternuson** [comment]
If you are not using a virtual environment, how did you do the initial Blinka setup?

**Comment by Ricker42** [comment]
To be honest I'm a bit hazy at this point as it was some months ago.  I was I believe following https://learn.adafruit.com/adafruit-sgp40/python-circuitpython for the most part.  I do remember seeing blinka now, and I believe I followed all the instructions found here https://learn.adafruit.com/circuitpython-on-raspberrypi-linux to install it.  The end of that showed a test program to run, but I didn't see where I had to be in a virtual environment, did I miss something?

Assuming everything is properly installed and configured from those pages, what are the correct steps I need to go through after powering up the Raspberry Pi and logging in (either on console or over ssh) to correctly run this?

**Comment by caternuson** [comment]
It's in that guide here:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi#setup-virtual-environment-3157129

The guide was updated to show venv usage starting with Bookworm...I think maybe a little over a year ago at this point.

I'd suggest starting over with the Blinka installation.

And then follow the SGP30 guide and example:
https://learn.adafruit.com/adafruit-sgp30-gas-tvoc-eco2-mox-sensor/circuitpython-wiring-test

Or is your board actually an SPG40?

**Comment by Ricker42** [comment]
My boards are SPG30's.

I see a potential problem...you missed my environment statement where I detailed I was running buster, not bookworm.

Rather than try to make this work in buster, I created a fresh SD with bookworm and followed those guides.  I found it to not be a straightforward process but I believe I got it working (one spot said to use "sudo pip3 install adafruit-circuitpython-sgp30" to install but that wasn't compatible with the venv so I just dropped the sudo and it seemed to work.


`(env) pi@raspberrypi:~ $ python3 sgp30demo.py 
SGP30 serial # ['0x0', '0x166', '0x76d6']
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
**** Baseline values: eCO2 = 0x8973, TVOC = 0x8aae
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 468 ppb
eCO2 = 400 ppm 	 TVOC = 468 ppb
eCO2 = 400 ppm 	 TVOC = 455 ppb
eCO2 = 400 ppm 	 TVOC = 440 ppb
eCO2 = 400 ppm 	 TVOC = 432 ppb
eCO2 = 400 ppm 	 TVOC = 425 ppb
eCO2 = 1440 ppm 	 TVOC = 2078 ppb
eCO2 = 8348 ppm 	 TVOC = 8623 ppb
eCO2 = 9408 ppm 	 TVOC = 10064 ppb
**** Baseline values: eCO2 = 0x8973, TVOC = 0x8aae
eCO2 = 19210 ppm 	 TVOC = 15197 ppb
eCO2 = 26639 ppm 	 TVOC = 22319 ppb
eCO2 = 27094 ppm 	 TVOC = 24690 ppb
eCO2 = 23290 ppm 	 TVOC = 21587 ppb
eCO2 = 17046 ppm 	 TVOC = 16064 ppb
eCO2 = 10503 ppm 	 TVOC = 13452 ppb
eCO2 = 6865 ppm 	 TVOC = 10751 ppb
eCO2 = 5273 ppm 	 TVOC = 9468 ppb
eCO2 = 4734 ppm 	 TVOC = 8680 ppb
^CTraceback (most recent call last):
  File "/home/pi/sgp30demo.py", line 25, in <module>
    time.sleep(1)
KeyboardInterrupt

(env) pi@raspberrypi:~ $ python3 sgp30demo.py 
SGP30 serial # ['0x0', '0x166', '0x76d6']
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
eCO2 = 400 ppm 	 TVOC = 0 ppb
`

The spike in TVOC was me spraying some rubbing alcohol on a paper towel and holding it under the sensor.

For others who find this, please confirm this is the proper way to set up to use this sensor off a Raspberry Pi with the i2c connector:

1) Raspberry Pi OS 12 (bookworm) or later
2) Install blinka as per https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi
3) Initiate virtual environment (venv): source env/bin/activate
4) Install library: pip3 install adafruit-circuit-python-sgp30
5) use python3 cli to execute program

Any time the Pi is rebooted, you need to do the following again:
1) Initiate virtual environment (venv): source env/bin/activate
2) use python3 cli to execute program

Is this correct?

**Comment by caternuson** [comment]
Cool. Looks like it's working as expected now?

And your statements about setup and operating all seem correct.

> (one spot said to use "sudo pip3 install adafruit-circuitpython-sgp30" to install but that wasn't compatible with the venv so I just dropped the sudo and it seemed to work.

Yep, don't use sudo. Sorry about that. This change is new enough that we still have old guides showing sudo. I just updated that guide to remove sudo.

Did you need to use buster for some reason? It should be able to work there using the same process. Python venv's have been available for some time. It's just only recently (bookworm) where the venv usage is "required". Gory details here:
https://learn.adafruit.com/python-virtual-environment-usage-on-raspberry-pi/overview

**Comment by Ricker42** [comment]
The only reason for using buster is that was what I had on the SD card.  Hadn't been using that particular Pi so hadn't done any updates or anything.

I have been able to cancel and restart multiple times, and after installing two additional libraries was able to resurrect the fuller program I had been working on that incorporates the temp/humidity sensor SI7021 and oled display SSD1306.

Closing this issue.
